[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient @ ^2.8
  miguelbalboa/MFRC522 @ ^1.4.10
build_flags =
  -D MQTT_MAX_PACKET_SIZE=512
